### ISSUE TITLE
view-source does not seem to set config.plugins.view-source.enabled

### ISSUE THREAD

**Issue by inktrap** [Perlkonig/grav-plugin-view-source#1]
I am using the following structure in my theme to display a link, depending wether view-source is enabled or not:

~~~
            {% if config.plugins.view-source.enabled %}                                                                                                                                         

            {% endif %}
~~~

Unfortunately this does not work and view-source does not seem set this setting.

I copied ``plugins/view-source/view-source.yaml`` to ``localhost/config/plugins/view-source.yaml`` (configuration by environment) and enabled view-source there (however, if it is enabled in ``config/plugins/`` this does not work either … seems like the plugin does not set this variable or uses the old plugin style (where plugin config was not user specific) …

Anyway, thanks for the great plugin :D

**Comment by Perlkonig** [comment]
I seem to remember there being a PHP problem with plugins with dashes. I think that's why I avoided  them in my later plugins. Try the following (not at a computer, so can't test) :

`{% if config.plugins['view-source'].enabled %}`

**Comment by inktrap** [comment]
Yes, now it works. 👍 Good to know, thanks! I am closing this, because it is not a bug in your plugin :)
